spring:
  profiles:
    active: local
#    active: deploy
  config:
    import: optional:file:.env[.properties]

jwt:
  secret:
    key: YjlmODZjOWVlYzlhNGE5MGI3NmE2M2E1ZmJkZGU3ZTFjODNmNmQyOTlkZmU0ZTc0OGU0NWNkOTFjYmZkNzQyNw==
    whitelist:
      - "/v3/api-docs/**"
      - "/swagger-ui/**"
      - "/swagger-resources/**"
      - "/swagger-ui.html"
      - "/api/auth/**"
    adminlist:
      - "/api/admin/**"
  token:
    prefix: "Bearer"
    expiration: 1800000

springdoc:
  override-with-generic-response: false